# Generated by Django 5.1.3 on 2025-04-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='notificaciones',
            field=models.BooleanField(default=True),
        ),
    ]
