# Generated by Django 5.1.3 on 2025-04-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesoregistrado',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
