# Generated by Django 5.1.3 on 2025-05-16 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kal_app', '0002_alter_pesoregistrado_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='carbohidratos_Consumidas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='diario',
            name='carbohidratos_a_Consumir',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='diario',
            name='grasas_Consumidas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='diario',
            name='grasas_a_Consumir',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='diario',
            name='proteinas_Consumidas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='diario',
            name='proteinas_a_Consumir',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='diario',
            name='calorias_Consumidas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='diario',
            name='calorias_a_Consumir',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pesoregistrado',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
